added check for cli args and step annotations

diff --git a/run b/run
--- a/run
+++ b/run
@@ -10,9 +10,19 @@ trap on_failure ERR # Set a trap to call the on_failure function if an error occ
 source src/getopts # Source the getopts script to parse command line options
 APP_PATH=$(pwd -P) # Get the absolute path of the current working directory
 
+if [[ -z "${input:-}" || -z "{$model:-}" ]]
+then
+  echo "ERROR: Both input (-i) and model (-m) arguments must be provided"
+  exit 1
+fi
+
 TIMESTAMP=$(date +"%Y-%m-%d_%H.%M.%S") # Get the current date and time in a specific format
 OUT_DIR="output/output_$TIMESTAMP" # Set the output directory path
 mkdir -p "$OUT_DIR" "$OUT_DIR"/tmp # Create the output and temporary directories
+
+echo ""
+echo "Housekeeping complete"
+echo ""
 
 # Executing matrix conversion
 singularity run \
@@ -26,6 +36,10 @@ singularity run \
   "${input}" 2>&1 \
   | tee -a "$APP_PATH"/"$OUT_DIR"/celltypist-log.txt
 
+echo ""
+echo "Counts sparse matrix to expression matrix conversion complete"
+echo ""
+
 # Executing celltypist
 singularity run \
   -B "$APP_PATH":/data \
@@ -36,6 +50,10 @@ singularity run \
   --outdir /data/"$OUT_DIR" \
   --majority-voting 2>&1 \
   | tee -a "$APP_PATH"/"$OUT_DIR"/celltypist-log.txt
+
+echo ""
+echo "CellTypist annotation prediction complete"
+echo ""
 
 # Executing application of predicted labels back onto input object
 singularity run \
@@ -49,5 +67,12 @@ singularity run \
   "${input}" 2>&1 \
   | tee -a "$APP_PATH"/"$OUT_DIR"/celltypist-log.txt
 
+echo ""
+echo "Application of predicted labels back onto input object complete"
+echo ""
+
 rm -rf "$OUT_DIR"/tmp # Remove the temporary directory
 
+echo ""
+echo "Annotation routine complete"
+echo ""
